### PR TITLE
Add symfony/validator to composer.json

### PR DESCRIPTION
**Pull request by covex-nn**
| Q             | A
| ------------- | ---
| Branch?       | "master", for 2.1 release
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| License       | MIT

In https://github.com/symfony-cmf/symfony-cmf/issues/260 i tried to create minimal recipes for SymfonyCMF bundles used in `symfony-cmf/symfony-cmf`

A recipe for `symfony-cmf/content-bundle` could contain these lines:

```yaml
cmf_content:
    persistence:
        phpcr:
            enabled: true
```

With this PR `symfony/validator` package will be added to composer.json. Service `validator.builder` is used in `ValidationPass` compiler pass

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
Thanks for your help. 
Btw: here a single installation gives a lot of infotmrmation. Btw: you should have a look into Testing. There is obe in travis doing pretty much as you did.

**Comment by covex-nn** [comment]
@ElectricMaxxx i found `installBundle()` in [check_install.sh](https://github.com/symfony-cmf/testing/blob/master/bin/scripts/check_install.sh). It is called when `"${TEST_INSTALLATION}" == true` and for `content-bundle` it is [failing](https://travis-ci.org/symfony-cmf/content-bundle/jobs/373530030). `installBundle` creates skeleton project v3.3 (btw, it is no longer supported by Flex), requires CMF bundle and checks if installation was successful.

To see how `content-bundle` actualy can be installed with Flex, (1) execute `composer create-project symfony-skeleton . ^3.4`, (2) add following lines to `require` section of composer.json:

```yaml
        "symfony-cmf/content-bundle": "2.1.x-dev",
        "symfony-cmf/core-bundle": "2.1.x-dev",
        "symfony-cmf/menu-bundle": "2.2.x-dev",
        "symfony-cmf/routing": "2.1.x-dev",
        "symfony-cmf/routing-bundle": "2.1.x-dev",
```

...  and run `composer update`. Then you will see error message:

> In CmfRoutingExtension.php line 132:
> 
> When the dynamic router is enabled, you need to either enable one of the persistence layers or set the cmf_routing.dynamic.route_provider_service_id option

That means, that some of bundles must be configured, i.e. have a recipe. After configuring `core-bundle` with following:

```yaml
cmf_core:
    persistence:
        phpcr:
            enabled: true
```

... you will see another error:

> In RegisterMappingsPass.php line 225:
> 
> Could not find the manager name parameter in the container. Tried the following parameter names: "cmf_menu.manager_name", "doctrine_phpcr.odm.default_document_manager"

That means, that a `doctrine_phpcr.odm.default_document_manager` must be created. Afaik it is created by `doctrine/phpcr-bundle` (and `doctrine/phpcr-odm` must be installed and a phpcr session must be cofigured). And now it became too complecated =)

I think, to solve this problem:
1. CMF bundles should require `doctrine/phpcr-bundle` and `doctrine/phpcr-odm`
2. `doctrine/phpcr-bundle` should create a fake-and-not-working-session if none is configured
3. on `fake-and-not-working-session` usage, there must be thrown an exception with instruction what to do next (how to composer require and how to configure)
4. `doctrine/phpcr-odm` should not require `phpcr/phpcr-implementation`

**Comment by ElectricMaxxx** [comment]
In that test  install is simply wanted to install one branch of one package to see if there are extra dependencies to load or base configuration to make. A nice and clean bundle should go green here. But mostly we are not, as we have the presistence implementation decission.
But having the reciepes: https://github.com/symfony-cmf/symfony-cmf/issues/259 will solve all your issues. Cause there i do exactly what your way of manually install is: require doctrine + dbal + main cmf bundles and pass a configuration for them. The reciepes make a green and nice point to start developing. You can try them both by setting the environ variable one by one. and installing them one by one. When phpcr is stable we will get the PR merged for the phpcr-pack, same for cmf.

**Comment by ElectricMaxxx** [comment]
BTW: i had the same aches like you have: https://gist.github.com/ElectricMaxxx/15dca79636d725e972a7e9471208cfd4

**Comment by covex-nn** [comment]
I saw both your PRs in `symfony/recipes-contrib` before, and as **Nyholm**, i think that all bundles must have there own recipes; and having it in mind i started to test CMF bundles how they can be installed with Flex separately, just to have alternative installation option.

Imagine:

1. You run `composer create-package symfony/skeleton .`
2. You run `composer require symfony-cmf/symfony-cmf`
3. Flex installs recipes for `doctrine/phpcr-bundle`, `symfony-cmf/core-bundle`, `symfony-cmf/block-bundle`, `symfony-cmf/menu-bundle`, `symfony-cmf/routing-bundle` and `symfony-cmf/content-bundle` without errors (just imagine =)
4. You run `composer require jackalope/jackalope-doctrine-dbal`
5. Flex installs recipe for `jackalope/jackalope-doctrine-dbal` (no errors again =)
6. You have fully functional SymfonyCMF =)

I understand, that it is just a fantasy. But i tried to reach it with my tests. Anyway, recipes for packs will allow to install SymfonyCMF clean, and i am waiting for it.

**Comment by dbu** [comment]
symfony-cmf/symfony-cmf is not a functional package, but more of trying to do what flex packs are without having actual flex... unless i am mistaken, @ElectricMaxxx started a pack to have cmf with phpcr storage. symfony-cmf/symfony-cmf should become obsolete in favor of the phpcr pack (and possibly orm pack one day)

**Pull request merged**
