### PR TITLE
move core, menu and routing bundle to dev

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
just for a try.

### CODE REVIEW

**Comment by dbu** [comment]
you would need the install test to see if this works at all. even then we don't know if its usable alone. you would need to look through the code to see where each of those bundles is used.

**Comment by dbu** [comment]
this is now in conflict with master.

**Comment by ElectricMaxxx** [comment]
Indeed, maybe we schould go over 2.0 branch, release and make a PR against master then. Or shall i rebase only?

**Comment by dbu** [comment]
you need to rebase this branch anyways. the 2.0 branch should always be merged to master after a commit has been merged to 2.0, master should not lag behind.

**Comment by ElectricMaxxx** [comment]
So rebase on master -> merge into 2.0 -> merge 2.0 into master, release 2.0.1 on branch 2.0 (and when we see installation test green on master)

**Comment by dbu** [comment]
i would not merge this to 2.0, only to master directly. and a PR starting from master can't be merged to 2.0 otherwise we would essentially merge master to 2.0 which would be wrong.

**Comment by ElectricMaxxx** [comment]
Instellation test shows the dependency on templating only now.

**Comment by ElectricMaxxx** [comment]
We should require twig-bundle then, cause templating component is kind of deprecated. We should do an equal split as done in routing-bundle.

**Comment by dbu** [comment]
ah true, twig bundle it should be then. and we should use the twig service instead of the templating component. is that possible without a BC break of the content controller? i guess we can remove the typehint on the constructor and accept both classes (templating or the twig equivalent).

what do you mean by "equal split"?

**Comment by ElectricMaxxx** [comment]
We changed the argument of the service depending if twig is available: https://github.com/symfony-cmf/routing-bundle/commit/36ea55cb3f8234db16a4cd997703edeae838e947 doing so we do not need to remove a interface, we just need to inject the correct service.

**Comment by dbu** [comment]
ah, right. yeah lets do that here too.

**Pull request closed without merging**
